name: gomintapa
description: 'A new Flutter project.'
publish_to: 'none' 
version: 1.0.0+1

environment:
    sdk: '>=3.4.3 <4.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    get: ^4.6.6
    mysql_client: ^0.0.27
    shared_preferences: ^2.2.3
    get_storage: ^2.1.1
    image_picker: ^1.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
flutter:
    uses-material-design: true
    assets:
        - assets/images/gmtp_logo_big.png
        - assets/images/gomintapa_logo.png
        - assets/images/home.png
        - assets/images/makmak.png
        - assets/images/tangtang.png
        - assets/images/home_selected.png
        - assets/images/makmak_selected.png
        - assets/images/tangtang_selected.png
        - assets/images/default_profile.png
        - assets/images/walk_dog.jpg
        - assets/images/dog.jpg
        - assets/images/jjanggu.jpg
        - assets/images/none_post.png
